[CONTENT REVIEW] 29 - Stranger Things - Atualiza Readme, eslint
betrybe/sd-0x-stranger-things-frontend pull request #10
Opened 2020-12-02 10:26 UTC by orlando-messias

CLOSES [issue](https://github.com/betrybe/course/issues/2343)

2020-12-02 17:38 UTC, nato-re approved these changes
Agora vai :shipit:, só dar pull e tirar o test.js

2020-12-07 11:43 UTC, LizzardMedeiros requested changes

2020-12-07 11:43 UTC, LizzardMedeiros commented on package.json
> +    "eslint": "^6.8.0",
```suggestion
    "eslint": "6.8.0",
```

2020-12-07 11:43 UTC, LizzardMedeiros commented on src/services/charactersAPI.js
> +const deafultTimeout = 30000;
```suggestion
const DEFAULT_TIMEOUT = 30000;
```

2020-12-07 11:43 UTC, LizzardMedeiros commented on src/services/charactersAPI.js
> +  constructor({ url = 'http://localhost:3000', timeout = deafultTimeout }) {
```suggestion
  constructor({ url = 'http://localhost:3000', timeout = DEFAULT_TIMEOUT }) {
```

2020-12-07 11:43 UTC, LizzardMedeiros commented on src/services/charactersAPI.js
> +  constructor({ url = 'http://localhost:3000', timeout = deafultTimeout }) {
está escrito `deafult`, não seria `default`?

2020-12-07 14:45 UTC, nato-re commented on src/services/charactersAPI.js
> +  constructor({ url = 'http://localhost:3000', timeout = deafultTimeout }) {
done

2020-12-07 16:04 UTC, roziscoding approved these changes

2020-12-07 17:07 UTC, merged